/* automatically generated by rust-bindgen 0.59.2 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub type __kernel_pid_t = ::aya_bpf::cty::c_int;
pub type pid_t = __kernel_pid_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct trace_entry {
    pub type_: ::aya_bpf::cty::c_ushort,
    pub flags: ::aya_bpf::cty::c_uchar,
    pub preempt_count: ::aya_bpf::cty::c_uchar,
    pub pid: ::aya_bpf::cty::c_int,
}
#[repr(C)]
pub struct trace_event_raw_sched_switch {
    pub ent: trace_entry,
    pub prev_comm: [::aya_bpf::cty::c_char; 16usize],
    pub prev_pid: pid_t,
    pub prev_prio: ::aya_bpf::cty::c_int,
    pub prev_state: ::aya_bpf::cty::c_long,
    pub next_comm: [::aya_bpf::cty::c_char; 16usize],
    pub next_pid: pid_t,
    pub next_prio: ::aya_bpf::cty::c_int,
    pub __data: __IncompleteArrayField<::aya_bpf::cty::c_char>,
}

